fixtures:
  repositories:
    zookeeper: "https://github.com/deric/puppet-zookeeper.git"
    java:      "https://github.com/puppetlabs/puppetlabs-java.git"
    stdlib:    "https://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
    kafka: "#{source_dir}"
